export const FIND_ALL_WIDGETS_FOR_TOPIC = 'FIND_ALL_WIDGETS_FOR_TOPIC';
export const DELETE_WIDGET = 'DELETE_WIDGET';
export const CREATE_WIDGET = 'CREATE_WIDGET';
export const UPDATE_WIDGET = 'UPDATE_WIDGET';
export const SAVE_ALL_WIDGETS = 'SAVE_ALL_WIDGETS';
export const SET_ALL_WIDGETS_FOR_TOPIC = 'SET_ALL_WIDGETS_FOR_TOPIC';
export const UPDATE_WIDGET_TYPE = 'UPDATE_WIDGET_TYPE';
export const UPDATE_PREVIEW = 'UPDATE_PREVIEW';
export const MOVE_WIDGET_UP = 'MOVE_WIDGET_UP';
export const MOVE_WIDGET_DOWN = 'MOVE_WIDGET_DOWN';
export const DRAG_WIDGETS_END = 'DRAG_WIDGETS_END';


